### ISSUE TITLE
How can this be set up with Compose?

### ISSUE THREAD

**Issue by mtheoryx** [markshust/Setup-an-Nginx-Proxy-for-a-Node.js-App-with-Docker#1]
I tried to make a docker-compose.yml file for spinning up both services.

The nodejs service is completely fine at localhost:3000

The nginx service just keeps giving me a 502 Bad Gateway.

Compose yml file:

```yml
nodejs:
  build: ./nodejs
  ports:
    - "3000:3000"

nginx:
  build: ./nginx
  links:
    - nodejs:nodejs
  ports:
    - "8000:80"
```

**Reference repo** 
[WIP branch getting Compose working](https://github.com/mtheoryx/docker-nginx-node-proxy/tree/wip-fix-nginx-502)

Appreciate any help you can provide, I'm kinda stumped!

**Comment by markshust** [comment]
I apologize for the belated reply. Here's a docker-compose that will run these containers. Note you need to link the node container with the `app` name so it's connected with the correct name the proxy can pickup.

```
web:
  build: ./nginx
  links:
    - app
  ports:
    - 8000:80

app:
  build: ./nodejs
```
